import { useQuery } from '@tanstack/react-query'
import { Activity, ArrowUpRight, FileText, TicketCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { patientApi } from '../../api/patientApi'
import { CurrentQueueCard } from '../../components/patient/CurrentQueueCard'
import { PatientNotificationList } from '../../components/patient/PatientNotificationList'
import { PeakHourCard } from '../../components/patient/PeakHourCard'
import { WaitTimeCard } from '../../components/patient/WaitTimeCard'
import { LoadingSkeleton } from '../../components/common/LoadingSkeleton'
import { PageHeader } from '../../components/common/PageHeader'
import { useAuthStore } from '../../stores/authStore'
import { formatTime } from '../../utils/date'

export function PatientDashboardPage() { const user = useAuthStore((s) => s.user); const forecasts = useQuery({ queryKey: ['peak-hours'], queryFn: patientApi.getPeakHours }); const notices = useQuery({ queryKey: ['notifications'], queryFn: patientApi.getNotifications }); if (forecasts.isLoading) return <LoadingSkeleton rows={6}/>; const list = forecasts.data ?? []; const now = list.find((x) => new Date(x.checkin_time).getHours() >= new Date().getHours()) ?? list[0]; return <><PageHeader title={`Xin chào, ${user?.full_name ?? 'bạn'}!`} description="Theo dõi lượt khám và nhận hướng dẫn theo thời gian thực."/><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">{now && <PeakHourCard forecast={now}/>}<div className="grid gap-5 sm:grid-cols-2"><CurrentQueueCard/><WaitTimeCard/></div></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><div className="card"><div className="mb-5 flex items-center justify-between"><h2 className="section-title"><Activity size={20}/>Dự báo check-in hôm nay</h2><span className="text-xs text-slate-400">Mỗi 30 phút</span></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={list}><defs><linearGradient id="forecast" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#0f766e" stopOpacity={0.3}/><stop offset="95%" stopColor="#0f766e" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="checkin_time" tickFormatter={formatTime}/><YAxis/><Tooltip labelFormatter={(v) => formatTime(String(v))}/><Area type="monotone" dataKey="predicted_checkin_count" name="Bệnh nhân dự kiến" stroke="#0f766e" strokeWidth={3} fill="url(#forecast)"/></AreaChart></ResponsiveContainer></div></div><PatientNotificationList items={notices.data ?? []}/></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Action to="/patient/checkin" icon={<TicketCheck/>} title="Lấy số khám"/><Action to="/patient/pathway" icon={<Activity/>} title="Xem lộ trình khám"/><Action to="/patient/results" icon={<FileText/>} title="Xem kết quả"/></div></> }
function Action({ to, icon, title }: { to: string; icon: React.ReactNode; title: string }) { return <Link to={to} className="group flex min-h-24 items-center gap-4 rounded-2xl border border-border bg-card p-5 font-bold text-foreground shadow-sm transition-all hover:-translate-y-1 hover:border-primary/30 hover:shadow-lg"><span className="icon-box">{icon}</span><span className="flex-1">{title}<small className="mt-1 block font-normal text-muted-foreground">Mở không gian chi tiết</small></span><ArrowUpRight size={18} className="text-muted-foreground transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-primary"/></Link> }
