import { useMutation } from '@tanstack/react-query'
import { BrainCircuit, CheckCircle2, HeartPulse, LockKeyhole, ShieldAlert } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import toast from 'react-hot-toast'
import { aiApi } from '../../api/aiApi'
import { patientApi } from '../../api/patientApi'
import { LoadingSkeleton } from '../../components/common/LoadingSkeleton'
import { PageHeader } from '../../components/common/PageHeader'
import { SymptomForm } from '../../components/patient/SymptomForm'
import type { SymptomFormData } from '../../schemas/symptomSchema'
import { useVisitStore } from '../../stores/visitStore'

export function SymptomPage() { const navigate = useNavigate(); const { visitId, setRecommendation } = useVisitStore(); const mutation = useMutation({ mutationFn: async (data: SymptomFormData) => { const id = visitId ?? 'VIS-260718-042'; await patientApi.submitSymptoms(id, data); return aiApi.symptomRouting(id, data) }, onSuccess: (result) => { setRecommendation(result); toast.success('AI đã hoàn tất đề xuất điều phối'); navigate('/patient/routing') }, onError: () => toast.error('Không thể phân tích triệu chứng') }); return <><PageHeader title="Khai báo triệu chứng" description="Mô tả chính xác giúp đội ngũ y tế ưu tiên và điều phối bạn đến đúng chuyên khoa."/>{mutation.isPending ? <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="card"><div className="mb-5 flex items-center gap-3"><span className="icon-box"><BrainCircuit className="animate-pulse"/></span><div><strong className="block text-foreground">AI đang phân tích triệu chứng</strong><span className="text-sm text-muted-foreground">Đang so sánh khoa, phòng và tải bệnh viện...</span></div></div><LoadingSkeleton rows={5}/></div><AnalysisSteps/></div> : <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><SymptomForm loading={mutation.isPending} onSubmit={(data) => mutation.mutate(data)}/><aside className="space-y-4 xl:sticky xl:top-24"><div className="rounded-2xl bg-[#082f34] p-5 text-white shadow-xl"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white/10"><HeartPulse/></span><h2 className="mt-4 text-lg font-bold">Thông tin giúp điều phối</h2><ul className="mt-4 space-y-3 text-sm text-teal-50/75">{['Mô tả vị trí và tính chất đau','Chọn thời điểm khởi phát','Đánh dấu mọi dấu hiệu nguy hiểm'].map((item) => <li key={item} className="flex gap-2"><CheckCircle2 size={17} className="shrink-0 text-teal-300"/>{item}</li>)}</ul></div><div className="card"><p className="flex items-center gap-2 font-bold text-foreground"><LockKeyhole size={18} className="text-primary"/>Bảo mật y tế</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Thông tin chỉ được chia sẻ với nhân viên có quyền tham gia lượt khám này.</p></div><div className="rounded-2xl border border-red-200 bg-red-50 p-4"><p className="flex items-center gap-2 font-bold text-red-800"><ShieldAlert size={18}/>Trường hợp khẩn cấp</p><p className="mt-1 text-sm leading-5 text-red-700">Nếu khó thở nặng, bất tỉnh hoặc chảy máu nhiều, hãy gọi 115 ngay.</p></div></aside></div>}</> }
function AnalysisSteps() { return <div className="card h-fit"><p className="font-bold">Tiến trình phân tích</p>{['Chuẩn hoá triệu chứng','Đánh giá mức ưu tiên','So sánh chuyên khoa','Tối ưu phòng chờ'].map((item,index) => <div key={item} className="mt-4 flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-full text-xs font-bold ${index < 2 ? 'bg-primary text-white' : 'bg-muted text-muted-foreground'}`}>{index + 1}</span><span className="text-sm font-medium">{item}</span></div>)}</div> }
