import argparse,json
from pathlib import Path
import numpy as np,pandas as pd
BASE={"CLINICAL_CONSULT":12,"ABDOMINAL_ULTRASOUND":15,"XRAY":8,"RESULT_REVIEW":5}
def generate(n=10000,days=45,seed=42):
    if n<10000 or not 30<=days<=60: raise ValueError("rows must be >=10000 and days must be between 30 and 60")
    rng=np.random.default_rng(seed); end=pd.Timestamp("2026-07-17 18:00",tz="Asia/Ho_Chi_Minh"); arrival=end-pd.to_timedelta(rng.uniform(0,days,n),unit="D")
    steps=np.resize(np.array(["INITIAL_CONSULT","DIAGNOSTIC_SERVICE","RESULT_PENDING","RETURN_REVIEW"]),n)
    service=np.where(steps=="INITIAL_CONSULT","CLINICAL_CONSULT",np.where(steps=="RETURN_REVIEW","RESULT_REVIEW",rng.choice(["ABDOMINAL_ULTRASOUND","XRAY"],n)))
    complexity=rng.choice(["SIMPLE","NORMAL","COMPLEX"],n,p=[.25,.55,.2]); cf=pd.Series(complexity).map({"SIMPLE":.8,"NORMAL":1,"COMPLEX":1.35}).to_numpy()
    active=np.array([BASE[x] for x in service])*cf*rng.lognormal(-.04,.25,n); interruption=np.where(rng.random(n)<.05,rng.gamma(2,2,n),0); wait=rng.gamma(2,6,n)*(1+rng.integers(0,12,n)/20)
    start=arrival+pd.to_timedelta(wait,unit="m"); finish=start+pd.to_timedelta(active+interruption,unit="m"); no_show=rng.random(n)<.04
    result_delay=rng.gamma(2,5,n); emergency=rng.random(n)<.02; failure=rng.random(n)<.02
    arrival_deviation=rng.normal(-10,45,n);appointment=arrival-pd.to_timedelta(arrival_deviation,unit="m");early=np.maximum(0,-arrival_deviation);checkin=arrival+pd.to_timedelta(rng.uniform(1,5,n),unit="m");eligible=pd.Series(checkin).combine(pd.Series(appointment-pd.to_timedelta(20,unit="m")),max).array;presence=rng.choice(["READY_AT_ROOM","CHECKED_IN_EARLY","IN_OTHER_SERVICE","AVAILABLE_ON_SITE"],n,p=[.72,.12,.1,.06]);cross=rng.integers(0,3,n);other_start=pd.Series(pd.NaT,index=range(n),dtype="datetime64[ns, Asia/Ho_Chi_Minh]");other_end=other_start.copy();mask=presence=="IN_OTHER_SERVICE";other_start.loc[mask]=pd.Series(arrival[mask]+pd.to_timedelta(5,unit="m"),index=np.where(mask)[0]);other_end.loc[mask]=other_start.loc[mask]+pd.to_timedelta(rng.gamma(2,6,mask.sum()),unit="m");predicted=other_end+pd.to_timedelta(rng.normal(3,2,n),unit="m")
    return pd.DataFrame({"journey_id":[f"j-{i//4}" for i in range(n)],"journey_step":steps,"task_id":[f"t-{i}" for i in range(n)],"parent_task_id":[None if i%4==0 else f"t-{i-i%4}" for i in range(n)],"depends_on_task_id":[None if i%4==0 else f"t-{i-1}" for i in range(n)],"patient_token":[f"P{i//4:06}" for i in range(n)],"queue_id":np.where(np.isin(steps,["INITIAL_CONSULT","RETURN_REVIEW"]),"CLINIC-A",np.where(service=="XRAY","XRAY-01","ULTRASOUND-01")),"task_type":np.where(steps=="RESULT_PENDING","DIAGNOSTIC_SERVICE",steps),"service_type":service,"clinical_priority":np.where(emergency,"EMERGENCY",rng.choice(["NORMAL","URGENT"],n,p=[.94,.06])),"readiness_status":np.where(steps=="RESULT_PENDING","RESULT_PENDING","COMPLETED"),"scheduling_mode":np.where(steps=="RETURN_REVIEW","SCHEDULED_WINDOW","FAIR_QUEUE"),"doctor_id":[f"D{x}" for x in rng.integers(1,8,n)],"device_id":[f"DEV{x}" for x in rng.integers(1,5,n)],"arrival_time":arrival,"appointment_start":appointment,"arrival_deviation_minutes":arrival_deviation,"early_arrival_minutes":early,"eligible_at":eligible,"presence_status":presence,"current_location":np.where(mask,"OTHER-ROOM","CLINIC-A"),"cross_room_task_count":cross,"other_service_started_at":other_start,"other_service_completed_at":other_end,"predicted_available_at":predicted,"actual_available_at":other_end,"missed_call":rng.random(n)<.025,"backlog_at_arrival_minutes":rng.gamma(2,6,n),"waiting_area_occupancy":rng.integers(0,40,n),"ready_at":arrival,"service_start":start,"service_end":finish,"result_ready_at":finish+pd.to_timedelta(result_delay,unit="m"),"result_urgency":rng.choice(["NORMAL","URGENT"],n,p=[.9,.1]),"result_delay_minutes":result_delay,"return_timing":rng.choice(["EARLY","ON_TIME","LATE"],n,p=[.15,.65,.2]),"schedule_window_start":pd.NaT,"schedule_window_end":pd.NaT,"queue_length":rng.integers(0,15,n),"arrival_rate_15m":rng.integers(0,8,n),"avg_service_30m":active+rng.normal(0,1,n),"resource_status":np.where(failure,"FAILED","AVAILABLE"),"resource_failure":failure,"doctor_pause":interruption>0,"case_complexity":complexity,"active_service_duration":active,"interruption_duration":interruption,"elapsed_service_duration":active+interruption,"actual_wait_time":wait,"no_show":no_show,"emergency_insertion":emergency,"recent_emergency_count":rng.poisson(.3,n)})
def main():
    p=argparse.ArgumentParser();p.add_argument("--rows",type=int,default=10000);p.add_argument("--days",type=int,default=45);p.add_argument("--seed",type=int,default=42);p.add_argument("--output",default="data/sample/synthetic.csv");a=p.parse_args();df=generate(a.rows,a.days,a.seed);out=Path(a.output);out.parent.mkdir(parents=True,exist_ok=True);df.to_csv(out,index=False)
    report={"rows":len(df),"days":a.days,"seed":a.seed,"assumptions":"SYNTHETIC_DEMO_NOT_CLINICALLY_CALIBRATED","missing_rate":df.isna().mean().to_dict(),"no_show_rate":float(df.no_show.mean()),"missed_call_rate":float(df.missed_call.mean()),"early_checkin_rate":float((df.presence_status=="CHECKED_IN_EARLY").mean()),"in_other_service_rate":float((df.presence_status=="IN_OTHER_SERVICE").mean()),"mean_early_arrival_minutes":float(df.early_arrival_minutes.mean()),"mean_backlog_at_arrival_minutes":float(df.backlog_at_arrival_minutes.mean()),"emergency_rate":float(df.emergency_insertion.mean()),"resource_failure_rate":float(df.resource_failure.mean()),"negative_duration_count":int((df[["active_service_duration","interruption_duration","elapsed_service_duration","actual_wait_time"]]<0).sum().sum()),"timestamp_order_invalid":int(((df.service_end<df.service_start)|(df.service_start<df.arrival_time)|(df.result_ready_at<df.service_end)).sum()),"duration_by_service":df.groupby("service_type").active_service_duration.agg(mean="mean",median="median",p80=lambda x:x.quantile(.8),p90=lambda x:x.quantile(.9)).to_dict()};out.with_suffix(".quality.json").write_text(json.dumps(report,indent=2),encoding="utf-8")
if __name__=="__main__":main()
